"""add relationship

Revision ID: a80a0dc568e2
Revises: 16bcf96186f5
Create Date: 2025-11-23 13:40:00.479640

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a80a0dc568e2"
down_revision: Union[str, Sequence[str], None] = "16bcf96186f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("group_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "students", "groups", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "students", type_="foreignkey")
    op.drop_column("students", "group_id")
    # ### end Alembic commands ###
